### ISSUE TITLE
en la definición del kext que hay que bloquear, hay un enabled=false que debe ser enabled=true

### ISSUE THREAD

**Issue by friguron** [ReinierTutoriales/Broadcom-Cards-macOS#2]
Pues eso, la definición de bloqueo está bien, debe ser excluded, pero si se deja el enabled = false, no funciona. Hay que realmente activarlo poiniendo a true el enabled. Hasta que no lo hice (viendo esta info correcta en otros foros), no dejó de darme Kernel Panics...

**Comment by ReinierTutoriales** [comment]
Gracias, ya lo active se me había olvidado.
